// Full lossless WOFF2 fonts with original cmap in standard private data. Generated by build-signature-font-web.py.
export const SIGNATURE_WEB_FONTS = {
  "mashanzheng": {
    "file": "MaShanZheng-Regular.woff2",
    "sha256": "fc7a43be592c1226a3311389106b1016170cab33927ea08e314debfed89b1b1a",
    "sourceSha256": "6d2546bb189c732a8ca29af9e22457b152387d158aa459e4ac2ce1e51788b7fb",
    "bytes": 3279386,
    "cmapBytes": 28918
  },
  "longcang": {
    "file": "LongCang-Regular.woff2",
    "sha256": "4e0bd65ee2f67d848e4dca5d64eace3f5f7df8d33dda6582a08d84a598c4a23a",
    "sourceSha256": "e5bf2c3f24ef2327c6f136d8f73e2f9dfdf44896fdbeb35a9515f44777bb91bc",
    "bytes": 2974052,
    "cmapBytes": 28920
  },
  "zhimangxing": {
    "file": "ZhiMangXing-Regular.woff2",
    "sha256": "9cc72a3b46bfb556a17fff2a14b2bc4501ddb10dc223690a99aacda3adcbf12b",
    "sourceSha256": "644e0cae9b40f0b10ab729a01bd32032e3973bac22be3dccae01bf6ae7fde969",
    "bytes": 2329292,
    "cmapBytes": 28920
  },
  "liujianmaocao": {
    "file": "LiuJianMaoCao-Regular.woff2",
    "sha256": "fde0c78ba491adbe9fc2d6cd5e40934819b4bb9d7f39e78217728a1e6c2a934e",
    "sourceSha256": "cab396b91a5b7c0b4005a35891180d06e6751f5ac261fe680aec65c1ae209033",
    "bytes": 2369212,
    "cmapBytes": 28920
  },
  "zcoolxiaowei": {
    "file": "ZCOOLXiaoWei-Regular.woff2",
    "sha256": "d183bed8c6af769fbbb1f5d1d648d54b565a3cbbb3655aced65aa0d166ed6880",
    "sourceSha256": "a42b620140f493db42f741351dfbf343c0936d58588ee8004b8b2a218d997ff1",
    "bytes": 2662062,
    "cmapBytes": 28926
  },
  "zcoolkuaile": {
    "file": "ZCOOLKuaiLe-Regular.woff2",
    "sha256": "fd5dcfc6e77a8af1806eec54580d87cd717b60b178ca7b368bc078f602ed222d",
    "sourceSha256": "812a6fc1fe54b6d73a419245c32dfeba8aa33104d5be90d1cf6af082007cb71d",
    "bytes": 900972,
    "cmapBytes": 29040
  }
} as const
