export const artworkPresets = [
  {
    id: 'portrait',
    title: '光影之间',
    category: '人物',
    src: '/artwork/portrait-reference.png',
    mode: 'charset',
    color: false,
    phrase: '',
    caption: '让每一个字符，留下光的形状。',
  },
  {
    id: 'landscape',
    title: '山河万里',
    category: '中文铺字',
    src: '/artwork/landscape.jpg',
    mode: 'phrase',
    color: true,
    phrase: '山河万里',
    caption: '把想说的话，写进山川。',
  },
  {
    id: 'color',
    title: '她的色彩',
    category: '彩色',
    src: '/artwork/portrait.jpg',
    mode: 'charset',
    color: true,
    phrase: '',
    caption: '细小字符，也有丰富的情绪。',
  },
  {
    id: 'pet',
    title: '一位老朋友',
    category: '人物',
    src: '/artwork/pet.jpg',
    mode: 'charset',
    color: false,
    phrase: '',
    caption: '换一种方式，记录陪伴。',
  },
  {
    id: 'sculpture',
    title: '时间的轮廓',
    category: '人物',
    src: '/demos/ascii-live/aristotle-bust.webp',
    mode: 'charset',
    color: false,
    phrase: '',
    caption: '经典的形状，新的表达。',
  },
  {
    id: 'words',
    title: '用文字看世界',
    category: '中文铺字',
    src: '/artwork/portrait-reference.png',
    mode: 'phrase',
    color: true,
    phrase: '光与影',
    caption: '一张照片，一句属于你的话。',
  },
] as const
export type ArtworkPreset = (typeof artworkPresets)[number]
